# Generated by Django 2.1.4 on 2018-12-30 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphql_api', '0002_auto_20181220_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gluon',
            name='prefix',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='gluon',
            name='relation',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='gluon',
            name='suffix',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='gluon',
            name='url',
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='quark',
            name='affiliate',
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='quark',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='quark',
            name='url',
            field=models.URLField(blank=True, max_length=255),
        ),
    ]
