# Generated by Django 2.1.4 on 2019-02-04 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graphql_api', '0003_auto_20181230_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gluon',
            name='gluon_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gluons', to='graphql_api.GluonType'),
        ),
    ]
