apiVersion: batch/v1
kind: Job
metadata:
  name: django-migrations
spec:
  template:
    spec:
      containers:
        - name: gluons-graphql
          image: euonymus/gluons-graphql:1.7
          command: ['python', 'manage.py', 'migrate']
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: password
            - name: DB_HOST
              value: postgres

      restartPolicy: Never
  backoffLimit: 5
