apiVersion: v1
kind: Service
metadata:
  name: gluons-graphql
  labels:
    name: gluons-graphql
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  selector:
    pod: gluons-graphql
  type: LoadBalancer
